language: android
sudo: false
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The BuildTools version used by this project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
jdk:
  - oraclejdk8
os:
  - linux
script:
  - ./gradlew build connectedCheck
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"